print("^2 ================================================================ ")
print("")
print("")
print("^1\t\t   RUBY CORE ALPHA")
print("^3\t      Tout est charger sans erreur!")
print("^3\tCore https://discord.gg/j8ENwKF")
print("")
print("\t\t^1Crée par Souki")
print("")
print("^2 ================================================================")